import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/Auth";
import "../globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <AuthProvider>
          <div className="bg-[#202123] max-w-xs min-h-screen overflow-y-auto md:min-w-[20rem]">
              <Sidebar />
            </div>
            <div className="bg-[#313338] flex-1">
              {children}
              <Toaster
                position="top-right"
                richColors
                closeButton
                duration={2000}
                pauseWhenPageIsHidden
                visibleToasts={1}
              />
            </div>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
